### ISSUE TITLE
Peer review 3

### ISSUE THREAD

**Issue by latana** [SheriefBadran/ApiClient#1]
Det var lite bökigt att få igång applikationen och var tvungen att ändra din webtoken i api.js filen på olika ställen. Något att kanske tänka på nästa gång.

Har användaren uppnått minimum längden på email eller password kommer det inte ut något meddelande. Där kunde varit något meddelande om att de är för kort.

Det är det bra struktur med dina kommentarer i din html. Det är lätt att det blir grötigt och svårt att navigera runt annars. Dock saknade jag liknande kommentarer på lite andra ställen.

Du har lite bort-kommenterad kod som också ligger och skrota på några få ställen.

Din kod är bra refaktorerad och det är lätt att gå igenom alla filer då det blir väldigt korta.

För övrigt så tycker jag att din kod är bra och det är riktigt snygg design!  Kul att du har testat på angulars css ramverk och att du skrivit din kod likt kommande angular 2.0. Det var en intressant inblick man fick. Förutom de punkter jag nämnt så ser jag inga problem med din applikation. Grymt jobbat!

**Comment by SheriefBadran** [comment]
Sant, jag såg till att min path var satt i konstruktorn, borde givetvis gjort det samma för api_nyckeln som man förmodligen ändrar oftare än en path.

**Comment by SheriefBadran** [comment]
Från början har loginformuläret endast visat röda fält när epost anges med ett ogiltigt format eller när lösenordet är kortare än servervalideringen kräver. Dock har formuläret visat ett felmeddelande då användaren trycker på knappen utan att dessa krav uppfylls eller att användarnamn/lösenord helt enkelt är felaktigt. Jag håller helt med om att endast ett rött fält kan förvirra användaren eftersom det inte talar om vad som är fel. Detta är nu åtgärdat så att även felmeddelanden visas.
